### ISSUE TITLE
github-actions user despite custom token

### ISSUE THREAD

**Issue by casperdcl** [softprops/action-gh-release#141]
Since late July/early August, using a custom `token: $MYBOT_TOKEN` no longer results in "**mybot** released this X days ago." Instead, it incorrectly says "**github-actions** released this X days ago." Example: https://github.com/iterative/shtab/releases

Is there a problem with `action-gh-release`? Or is it another accidental breaking change GH made (to be reported at https://github.community)?

**Comment by softprops** [comment]
Hi there. I see your last release was 4 days ago and your using an env var for the token
  
  You were likely caught in a breaking change that was fixed just yesterday 

https://github.com/softprops/action-gh-release/releases/tag/v0.1.8

the breaking change was a merge of a pr that introduced resolving the token from an input falling back on an env var. the breaking change was that the input was declared with a default of the actions provided token which always exists meaning the env var would never get used. The fix for backwards compat was to swap the resolution order to look for the env var and then the input

**Comment by casperdcl** [comment]
Ah related #132, fixed by #133
